tornado:
  image: ibotdotout/python-opencv:latest
  volumes:
    - ./:/code
  devices:
     - /dev/video0:/dev/video0
  working_dir: /code
  ports:
    - 8080:8080
  command: /bin/bash -c "ln /dev/null /dev/raw1394 && pip install -r requirements.txt && exec python start.py"
